### ISSUE TITLE
QL server hosting

### ISSUE THREAD

**Issue by ozh** [MinoMino/minqlx#26]
A bit off topic but still of general interest for minqlx users I think: it would be nice if users could share their experience on where to host their QL + minqlx instance (price / number of concurrent players / location for instance)

**Comment by MinoMino** [comment]
Given it's not one of those services that does everything for you instead of giving you SSH access to a clean server, then pretty much any server that can host a QLDS should be good for minqlx, though. Perhaps I'm wrong, but I think the Steam forums would be more appropriate and probably more helpful. In any case, I'm keeping this issue open for now so people can chime in.

In my case, I've been using vultr.com. I host 10 QLDS instances on the $16/month VPS, although nowadays just one or two of them has players most of the time. I got it in Germany, although I used to have it in Netherlands. The latter unfortunately had some bad days occasionally and would experience packet loss to all players for a couple of minutes, like 2-3 times a day. Switching to Germany fixed it. It usually hosts like 30-ish players during prime time, but around the time after the Steam-only update was released it would have like 80-ish people some days without issues. All in all, they're pretty good and they're cheaper than for instance DigitalOcean ($20/month for more or less the same), which seems to be pretty popular for QLDS hosting. I'll still probably switch to another host or downgrade to a cheaper instance in the near future because of the $16/month one being a bit overkill for 30-ish players, though. Oh, and when I ordered it they also had like a $50 in free credit campaign too, so in fact I have yet to pay a single dollar for it. Not sure if that's still around, though.

Anyway, if anyone reading this ever feels like trying out vultr, [here's a referral link](http://www.vultr.com/?ref=6855904).

**Comment by Melodeiro** [comment]
The optimal choise (perfomance/price) is to use VPS based on KVM system. Any VPS should work, you just need to be sure, that they are stable.

My DigitalOcean 5 usd instance has CPU loading up to 25% with full server (16 players), and 1 server afaik needs just 100 MB of RAM to work. Anyway i don't have many expirience with it, and maybe qlds sometimes causes overloads. Also DigitalOcean has great support, they always try to help you, even if there is no fault on their side. And i have not noticed any problems with as well as Amsterdam and Frankfurt servers.

Will post here [refferal link](https://www.digitalocean.com/?refcode=0bf6a2ddc902) too because if you was invited by someone, you will get 10 on your account. Keep in mind, they are sometimes charge 5 usd which goes to account for allowing you to use instances, but sometimes it is not required. Maybe depends on country, from where you are registered.

You also may try Amazon AWS since they give free VPS for 1 year. It should be pretty stable service. The problem is that they just allow to use it in USA for new customers, but it seems that they may do exceptions... if you are persuasive enough.
