### ISSUE TITLE
Developer docs

### ISSUE THREAD

**Issue by jamesla** [MinoMino/minqlx#52]
I haven't used minqlx before and want to write a simple plugin to auto ready players as soon as the round starts. 

Where can I find the developer docs and maybe a hello world type plugin?

**Comment by dsverdlo** [comment]
"Auto ready players as soon as the round starts"?

For a hello world I suggest you look at existing plugins (https://github.com/MinoMino/minqlx/wiki/Useful-Plugins)

**Comment by notallmighty** [comment]
I would also like to know some more specs about it. I would require to implement <gc> garbage collector for a plugin.

**Comment by MinoMino** [comment]
@jamesla There's no documentation. I was going to set up Sphinx, but never got around to it and I don't actively work on this anymore. I've commented a decent amount of the code though, for what it's worth. The stuff in the `python/minqlx` directory is what you'll want to look at. Although looking at plugins is probably the easiest way to get familiar with how stuff works.

Some of the plugins in [the official repo](https://github.com/MinoMino/minqlx-plugins) are pretty simple. Like `permission`, `motd`, `raw`, and so on. And like mentioned, looking at custom ones can be good as well. Sorry for the inconvenience.

EDIT: Found another simple plugin I had lying around as well that could work as a reference: [`bots`](https://gist.github.com/MinoMino/a28545d16fe5cac5d1f8)

@notallmighty What do you mean with a garbage collector? It's all Python, so all you need to do is drop references for things to get GC'd.

**Comment by MinoMino** [comment]
Oh, and [here's a hello world type of plugin I had lying around](https://gist.github.com/MinoMino/b0312e302bd90719ce5a).

**Comment by notallmighty** [comment]
@MinoMino i know, i know. The thing is: plugin fun.py after few hours running, and use causes lag. Also, people with lower spec systems complain just straightforward about it, causing them lag. Python itself clean it up periodically, what is OK for low server's load times, like morning. But usually with 12-20 fancy guys spamming strange sounds on any possible occasion, server's load goes up, and performance down. Part of this i am sure is the sound plugin. Part for sure ql itself, with ql we can't do anything. But optimizing plugin by forcing gc could help. Server runs in x64 mode on 2,2ghz x2 with 6Gb ram and 1Gbit link, so it has enough power to run ql smoothly. 
@MinoMino so maybe you could have an idea to make plugin performing better. Sounds are made along your specification.

**Comment by MinoMino** [comment]
@notallmighty I doubt the sounds are causing any significant load on the server, and even in the case that it does, I don't see how forcing Python to GC is going to help. GCing is all about freeing memory and on a system with 6 GB RAM, there's no way sounds are going make it start using swap space either. If anything, forcing GC more often that it's scheduled to is only going to increase load.

In the case that you don't believe me, let me fill you in on what playing sounds makes the server do. *Every* single time someone chats, `fun` will run a series of regex matches on it to figure out if it triggers any sounds. If it does, it checks whether or not it's been at least `qlx_funSoundDelay` seconds since last sound. If it has, then iterate through every player and check if they've set the flag to opt out of sounds, and skip them if they have. Now the playing of the sound itself is extremely simple. It's done through a server command with the path to the sounds. In other words, the sound itself isn't sent through the server by any means. In fact, for every player that holds tab to see the scoreboard, the server's already sending commands at a frequency *way* higher than sounds ever do.

So the only "weak" point would be the regex matching for every line of chat, but I can bet you it's going to be insignificant. Use `timeit` to check if you want to make sure. Now, if the client has a memory leak as a consequence of having sounds play, then there's nothing I can do about that. Fortunately there's a way to opt out of sounds, so that's shouldn't be an issue for those with low memory.

So what I'm trying to say is that I can't see how sounds are causing any issue, and even if there's something I'm overlooking, then I can assure you we're looking at a rare issue I, and most others, can't reproduce considering I've ran my servers for months without restarting on a box with a fraction of the resources you have, yet both load and memory have been at regular levels. Of course, if you discover any leads, then I'll happy have a look at it, but I have none right now.

**Comment by jwinett** [comment]
@jamesla - You can do that by setting g_doWarmup to 0, I think.
