### ISSUE TITLE
Scoreboard damage disapears

### ISSUE THREAD

**Issue by saltyscootertrash** [MinoMino/minqlx#89]
Anyone know why and if there is a fix for losing the scoreboard damage during large ca games, 12 per team and over?

**Comment by em92** [comment]
I remember, there was a plugin that fixes massive kicking due to overflow stuff, but takes out scoreboard values. What plugins are used?

**Comment by saltyscootertrash** [comment]
Hi Eugene, I know the plugin you are talking about but this problem has been going on servers since before the use of that plugin.

**Comment by tjone270** [comment]
The reason this occurs is due to the fact that the Quake Live scoreboard protocol was never designed to accommodate more than a certain number of players in-game at a time. As soon as this limitation is reached, shorter scoreboard messages are sent by the server to allow the scoreboard to still show accurate though limited information. There is a CVAR that turns this functionality on at all times - don’t remember what it is right now though. 

Sponge mentioned this in release notes for v1068:
‘- handle too big scoreboard messages a little better by falling back to a smaller message. some elements of the scoreboard will still be out of date on large servers after this, but the basics will be correct.’

This is a Quake Live bug.

**Comment by saltyscootertrash** [comment]
Thanks for the info tjone270.
